
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: 
    url: jdbc:mysql://localhost:3306/test
    username: root	
    password: root
    driverClassName: 
